version: '2'
services:
  postgres-db:
    image: postgres:15
    environment:
      PGDATA: /var/lib/postgresql/data
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
    - postgres_data:/var/lib/postgresql/data
    ports:
    - 5435:5432/tcp
    networks:
      - my-network

  mysql-db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=data_staging
      - MYSQL_USER=root
      - MYSQL_PASSWORD=erik
      - MYSQL_ROOT_PASSWORD=erik
    ports:
      - 3307:3306/tcp
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my-network
volumes:
  mysql_data: # docker volume create mysql_data
    external: true
  postgres_data: # docker volume create postgres_data
    external: true

networks:
  my-network:
    external: true
